yarnPath: .yarn/releases/yarn-4.9.0.cjs # TODO: corepack does not work in github actions on windows
nodeLinker: node-modules
npmPublishRegistry: https://registry.npmjs.org
npmAuthToken: ${NPM_TOKEN:-}
checksumBehavior: ignore
plugins:
  - ./.yarn/custom-plugins/snapshot-no-semver-range.cjs
