checksumBehavior: ignore

nodeLinker: node-modules

npmAuthToken: '${NPM_TOKEN:-}'

npmPublishRegistry: 'https://registry.npmjs.org'

plugins:
  - ./.yarn/custom-plugins/snapshot-no-semver-range.cjs

yarnPath: .yarn/releases/yarn-4.12.0.cjs
