{
 "title": "Hive Gateway",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Gateway Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "GraphQL response time",
   "type": "timeseries",
   "description": "The time needed to successfuly respond to GraphQL requests for quantiles p95, p90, p75 and p50.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(graphql_yoga_http_duration_bucket{url=~\".*/graphql$\", statusCode=\"200\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(graphql_yoga_http_duration_bucket{url=~\".*/graphql$\", statusCode=\"200\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(graphql_yoga_http_duration_bucket{url=~\".*/graphql$\", statusCode=\"200\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(graphql_yoga_http_duration_bucket{url=~\".*/graphql$\", statusCode=\"200\"}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "GraphQL Requests per seconds",
   "type": "timeseries",
   "description": "Number of GraphQL request per seconds for each status codes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(statusCode) (rate(graphql_yoga_http_duration_count{url=~\".*/graphql$\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Subgraphs metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Subgraphs response time",
   "type": "timeseries",
   "description": "Response time of each subgraphs with quantiles p95, p80 and p50.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, subgraphName) (rate(graphql_gateway_subgraph_execute_duration_bucket[$__rate_interval])))",
     "legendFormat": "{{subgraphName}} p95"
    },
    {
     "expr": "histogram_quantile(0.80, sum by(le, subgraphName) (rate(graphql_gateway_subgraph_execute_duration_bucket[$__rate_interval])))",
     "legendFormat": "{{subgraphName}} p80"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le, subgraphName) (rate(graphql_gateway_subgraph_execute_duration_bucket[$__rate_interval])))",
     "legendFormat": "{{subgraphName}} p50"
    }
   ]
  },
  {
   "title": "Subgraph requests per second",
   "type": "timeseries",
   "description": "Number of request per second for each subgraph.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(subgraphName, ) (rate(graphql_gateway_subgraph_execute_duration_count[$__rate_interval]))",
     "legendFormat": "{{subgraphName}} p95"
    }
   ]
  },
  {
   "title": "Subgraph errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by(subgraphName) (rate(graphql_gateway_subgraph_execute_errors[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Internal Insights", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Deprecated field used last 24h",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(graphql_envelop_deprecated_field[24h]))",
     "legendFormat": "Deprecated fields"
    }
   ]
  },
  {
   "title": "Schema changes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum(rate(graphql_envelop_schema_change[$__rate_interval]))",
     "legendFormat": "Schema changes"
    }
   ]
  },
  {
   "title": "Parse phase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(graphql_envelop_phase_parse_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(graphql_envelop_phase_parse_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(graphql_envelop_phase_parse_bucket[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum by(le) (rate(graphql_envelop_phase_parse_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Validate phase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(graphql_envelop_phase_validate_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(graphql_envelop_phase_validate_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(graphql_envelop_phase_validate_bucket[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(graphql_envelop_phase_validate_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Context Building phase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(graphql_envelop_phase_context_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(graphql_envelop_phase_context_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(graphql_envelop_phase_context_bucket[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(graphql_envelop_phase_context_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Execute phase",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(graphql_envelop_phase_execute_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(graphql_envelop_phase_execute_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(graphql_envelop_phase_execute_bucket[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(graphql_envelop_phase_execute_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}